services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=development
            - DATABASE_URL=${DATABASE_URL}
            - AUTH_SECRET=${AUTH_SECRET}
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
            - RESEND_API_KEY=${RESEND_API_KEY}
            - NEXT_PUBLIC_APP_URL=http://localhost:3000
            - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
            - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
            - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
        env_file:
            - .env
        volumes:
            - .:/app
            - /app/node_modules
            - /app/.next
        restart: unless-stopped
        command: npm run dev
